name: Publish

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit Information
        id: commit
        run: |
          echo "commit_id=commit-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Npm
        run: |
          npm install
      - name: Less
        run: |
          ./node_modules/less/bin/lessc assets/css/_main.less assets/css/_main.css
          ./node_modules/clean-css-cli/bin/cleancss assets/css/_main.css -o assets/css/main.css -O1 -O2 "restructureRules:on"
          rm assets/css/_main.css
      - name: Prepare build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git clone --single-branch --branch=gh-pages --depth=1 --no-checkout "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" _site
      - name: Build Site
        run: |
          PAGES_REPO_NWO="${GITHUB_REPOSITORY}"
          export PAGES_REPO_NWO
          bundle exec jekyll build --trace --profile
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          pushd _site/ &>/dev/null
          : > .nojekyll
          git add -A
          git -c user.name=GitHub -c user.email=noreply@github.com commit -m "${{ steps.commit.outputs.commit_message }}" -m "Based on commit ${{ steps.commit.outputs.commit_id }}, from GitHub Actions build ${{ github.run_number }}"
          git push
          popd &>/dev/null
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: _site
          retention-days: 1
      - name: Update Algolia index
        run: |
          bundle exec jekyll algolia push
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        if: env.ALGOLIA_API_KEY != ''
        continue-on-error: true
